module.exports = {
  fieldData: {
    connectionConfigId: '数据标识',
    name: '数据连接名称',
    nameHelper: '名称内不能带有特殊标识',
    databaseType: '数据库类型',
    databaseTypeHelper: '数据库的类型',
    host: '主机名或IP地址',
    hostHelper: '数据库的主机名或IP地址',
    port: '端口号',
    portHelper: '数据库的主机名或IP地址的端口号',
    userName: '用户名',
    userNameHelper: '数据库的用户名',
    password: '登录密码',
    passwordHelper: '数据库的登录密码',
    schema: 'Schema/数据库',
    schemaHelper: '数据库名',
    encoding: '编码',
    encodingHelper: '数据库的编码',
    sshHost: 'SSH主机名',
    sshHostHelper: '数据连接的SSH主机名',
    sshPort: 'SSH端口',
    sshPortHelper: '数据连接的SSH端口',
    localPort: 'SSH本地端口',
    localPortHelper: '数据连接的SSH本地端口',
    remotePort: 'SSH远端端口',
    remotePortHelper: '数据连接的SSH远端端口',
    sshUser: 'SSH用户名',
    sshUserHelper: '数据连接的SSH用户名',
    sshPassword: 'SSH用户密码',
    sshPasswordHelper: '数据连接的SSH用户密码',
    createTime: '添加时间',
    operate: '操作',
  },
  connectionType: {
    TCP_IP: 100,
    SSH: 101,
  },
};
