module.exports = {
  fieldData: {
    comboName: '套餐名称',
    comboTitleAddHelper: '请输入套餐名称，不超过32个字',
    merchantProductId: '商家产品编号',
    merchantProductIdHelper: '商家产品编号在产品保存后不可更改',
    productCategory: '产品品类',
    productFirst: '美食',
    productSecond: '亲子',
    productThree: '娱乐',
    productFour: '其他',
    comboFeature: '套餐特色',
    comboFeatureHelper: '请输入套餐特色，不超过50个字',
    phone: '联系电话',
    purchaseAstrict: '购买限制',
    comboInclude: '套餐包含',
    comboHaveNo: '套餐不含',
    reserveExplain: '预定说明',
    useExplain: '使用说明',
    backExplain: '退改说明',
    importantNote: '重要提示',
  },
};
