module.exports = {
  fieldData: {
    userOrderId: '订单编号',
    realName: '站长姓名',
    tradeNo: '订单流水号',
    type: '订单类型',
    state: '订单状态',
    dateRange: '提交时段',
    title: '商品名称',
    subtitle: '副标题',
    origin: '产地',
    number: '编号',
    specification: '规格',
    unit: '单位',
    buyType: '销售渠道',
    saleType: '销售类型',
    rank: '所属类别',
    shareTitle: '分享标题',
    shareDescription: '分享描述',
    image: '图片',
    stock: '库存',
    costPrice: '进货价格',
    price: '销售价格',
    expressPrice: '配送价格',
    marketPrice: '市场价格',
    stockPrice: '服务站价格',
    pushMoney: '提成',
    score: '积分',
    access: '访问量',
    publishTime: '发布时间',
    productAmount: '商品金额',
    payAmount: '实收金额',
    note: '修改原因',
  },
};
