module.exports = {
  fieldData: {
    regUserId: '会员标识',
    nickname: '会员昵称',
    type: '会员类型',
    dateRange: '注册时段',
    parentId: '用户上级标识',
    phone: '联系电话',
    noId: '身份证号',
    headPortraits: '头像信息',
    email: '邮箱账户',
    birthday: '生日日期',
    sex: '会员性别',
    province: '省份城市',
    address: '详细地址',
    isReceiveOTMsg: '订单消息',
    isManage: '管理权限',
    parentNickname: '用户上级昵称',
    parentRealName: '用户上级姓名',
  },
};
