module.exports = {
  fieldData: {
    realName: '站长姓名',
    phone: '联系电话',
    mName: '所在社区',
    lineId: '配送线路',
    state: '审核状态',
    dateRange: '统计时段',
    userId: '用户Id',
    phoneSpare: '紧急联系电话',
    cardNo: '身份证号',
    bankName: '开户银行',
    bankNo: '银行卡号',
    isPay: '是否缴费',
    isClose: '采购',
    isCloseShop: '店铺开关',
    isDisplay: '是否显示',
    area: '省份-城市-县区',
    address: '详细地址',
    longitude: '经度',
    latitude: '纬度',
    cardUrl: '正面证件照',
    reverseUrl: '反面证件照',
    cityName: '所属地区',
    map: '地点标记（移动地图后，中心点坐标将被选取，详细地址与经维护信息将自动获取填充）',
    mapShow: '地点标记（拖动地区可以查看周边）',
  },
};
