module.exports = {
  fieldData: {
    merchantSaleStatisticId: '数据标识',
    merchantName: '站点名称',
    realName: '站长姓名',
    areaAgent: '地区账户',
    areaAgentId: '地区账户标识',
    areaAgentName: '地区账户名称',
    mode: '统计模式',
    modeNote: '统计模式',
    // saleAmount: '销售总金额',
    // onlineSaleAmount: '线上金额',
    // offlineSaleAmount: '线下金额',
    timeFrame: '统计时段',
    channel: '统计来源',
    channelNote: '统计来源',
    createTime: '统计时间',
    autoRemark: '自动备注',
    ip: '统计服务IP',
  },
};
