module.exports = {
  fieldData: {
    goodsOutboundMerchantRecordId: '标识',
    lineId: '线路标识',
    lineName: '线路名称',
    productName: '品名',
    specification: '规格',
    unit: '单位',
    productCount: '数量',
    rankId: '品类标识',
    productId: '产品标识',
    minCostPrice: '最小成本价',
    averageCostPrice: '平均成本价',
    maxCostPrice: '最大成本价',
    minSalePrice: '最小售价',
    averageSalePrice: '平均售价',
    maxSalePrice: '最大售价',
    minStockPrice: '最小站长价',
    averageStockPrice: '平均站长价',
    maxStockPrice: '最大站长价',
    totalCostPrice: '总计成本价',
    totalSalePrice: '总计售价',
    totalStockPrice: '总计站长价',
    areaAgentId: '所属地区',
    batchDate: ' 出库批次',
  },
};
